---
title: "Demographic Data Summaries for AZA Pygmy Loris Provisional SSP"
author: "Alicia Rich"
output:
  html_document:
    theme:
      bootswatch: litera
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    code_folding: "show"
    fig_caption: true
    df_print: paged
params:
  sampleset: "loris"
  dataset: "culi"
                     
---

```{r global, message = FALSE}
global             <- config::get(config = "default")

here::i_am("DemographicsLorises_v3.Rmd")
source(here::here(global$setup))

source(here(path$AZAstudbooks$functions))
```

# Function to clean and standardize each dataset


```{r}
alive <- read.csv(here(path$AZAstudbooks$living25)) %>% 
  filter(Current.Status == "Alive") %>% pull(Studbook.ID) %>% c(2638)

loc.extra <- tibble(
  Institution.Name = c(rep("Wild", times = 5), 
           "Private Owner", 
           "Virginia Safari Park"),
  Mnemonic = c(
            "Vietnam", 
            "Thailand", 
            "LAOPEOPLESDEMOCRATICREPUBLIC", 
            "Undetermined", 
            "Asia", 
            "Greenwich", 
            "VASAFARI"),
  Country = c("Vietnam", 
              "Thailand", 
              "Laos", 
              rep("Undetermined", times = 2), 
              "United Kingdom", 
              "United States")
)

locations <- bind_rows(read.csv(here(path$AZAstudbooks$institutions$current25)), 
                       read.csv(here(path$AZAstudbooks$institutions$current21)), 
                       read.csv(here(path$AZAstudbooks$institutions$historic21)),
                       loc.extra) %>% clean.locations()
```


```{r, warning = FALSE}
living.25   <- read.csv(here(path$AZAstudbooks$living25))   %>% clean_studbook(., alive, locations)
living.21   <- read.csv(here(path$AZAstudbooks$living21))   %>% clean_studbook(., alive, locations) %>%
  filter(!(ID %in% pull(living.25, ID)))
historic.21 <- read.csv(here(path$AZAstudbooks$historic21)) %>% clean_studbook(., alive, locations) %>%
  filter(!(ID %in% pull(living.25, ID))) %>%
  filter(!(ID %in% pull(living.21, ID)))
hypotheticals <- tibble(
  Studbook.ID    = rep(c(12108, 12717, 22717, 11045, 12423), each = 2),
  Sex.Type       = rep(c("M", "M", "F", "M", "M")      , each = 2),
  Current.Status = "Deceased",
  Location       = rep(c("IRCHEL", "GREENWICH", "GREENWICH", "POZNAN", "PUBLIC"), each = 2),
  Sire           = 0,
  Dam            = 0,
  Date           = c("10/Apr/1987", 
                     "10/Apr/1988", 
                     rep(c("12/Jun/2019", "12/Jun/2020"), times = 2),
                     "14/Feb/1985",
                     "14/Feb/1988",
                     "01/Jan/1997",
                     "01/Jan/2002"
                     ),
  Event.Type     = rep(c("Birth/hatch", "Go Ltf"), times = 5)
) %>% 
  clean_studbook(., alive, locations)

```

```{r}
missing <- tibble(
 ID           = 2638,
 Sex          = "F",
 Status       = "A",
 Sire         = 1121,
 Dam          = 1145,
 OrderLoc     = 1,
 Date         = ymd("2011-06-14"),
 TypeEvent    = "Birth",
 Location     = "MOO",
 NameLoc      = "Aquarium & Rainforest at Moody Gardens",
 Country      = "United States"
)
```


# Merge all data

```{r}
studbook <- bind_rows(living.25, 
                      living.21, 
                      historic.21, 
                      hypotheticals, 
                      missing) %>%
  mutate(TypeEvent = fct(TypeEvent, 
                         levels = c("Birth", "Transfer", "End")),
         across(c(Sire, Dam), ~ na_if(., 0))) %>%
  arrange(ID, OrderLoc, TypeEvent) %>%
  distinct() %>%
  group_by(ID) %>%
  mutate(StartLoc = if_else(TypeEvent != "End", Date, lag(Date)),
         EndLoc   = if_else(TypeEvent == "End", Date, lead(Date))) %>%
  select(
    ID,
    Status,
    OrderLoc,
    Location,
    TypeEvent,
    StartLoc,
    Date,
    EndLoc,
    NameLoc,
    Country,
    Sex,
    Sire,
    Dam
  ) %>% ungroup()


end.records <- studbook %>%
  select(ID,
         Status,
         OrderLoc,
         Location,
         TypeEvent,
         StartLoc,
         Date,
         EndLoc
  ) %>%
  slice_tail(n = 1, by = ID) %>%
  filter(TypeEvent != "End") %>%
  mutate(Date = if_else(Status == "A", today(), NA),
         TypeEvent = "End") %>% 
  mutate(EndLoc = Date) %>%
  select(-Status) %>% distinct()
```


```{r, warning = FALSE}
timeline <- studbook %>%
  filter(TypeEvent == "Birth" & !is.na(Sire)) %>%
  select(ID      = Sire,
         OffspID = ID,
         Location,
         Date) %>%
  bind_rows(select(filter(studbook, TypeEvent == "Birth" & !is.na(Dam)),
                   ID      = Dam,
                   OffspID = ID,
                   Location,
                   Date)) %>%
  left_join(select(studbook,
                   ID,
                   OrderLoc,
                   Location,
                   StartLoc,
                   EndLoc
                   ), by = join_by(ID, Location)) %>%
  mutate(check = if_else(
    between(Date, StartLoc, EndLoc) | 
      is.na(StartLoc) & Date < EndLoc | 
      is.na(EndLoc) & Date > StartLoc | 
      (is.na(StartLoc) & is.na(EndLoc)) | is.na(Date),
    "keep",
    "discard"
  )) %>% filter(check == "keep") %>%
  mutate(TypeEvent = "Breed") %>%
  select(-c(check, OffspID)) %>% 
  bind_rows(end.records) %>%
  distinct() %>% 
  arrange(ID, 
          OrderLoc,
          Date) %>%
  bind_rows(select(studbook,
                   ID,
                   OrderLoc,
                   Location,
                   TypeEvent,
                   StartLoc,
                   Date,
                   EndLoc)) %>% 
  distinct() %>% 
  mutate(TypeEvent = fct(TypeEvent, levels = c(
    "Birth",
    "Transfer",
    "Breed",
    "End"
  ))) %>%
  arrange(ID, 
          OrderLoc,
          TypeEvent,
          Date) %>%
  select(ID,
         OrderLoc,
         Location,
         StartLoc,
         TypeEvent,
         Date,
         EndLoc) %>%
  group_by(ID) %>%
  mutate(Date = case_when(
    is.na(Date) & TypeEvent != "End"  & TypeEvent != "Breed" ~ StartLoc,
    is.na(Date) & TypeEvent == "End"  ~ EndLoc,
    is.na(Date) & TypeEvent == "Birth" ~ lead(Date) - years(1),
    is.na(Date) & TypeEvent == "Transfer" & lead(TypeEvent) != "End" ~
      lag(Date) + days(floor(as.numeric(as.period((interval(lag(Date), lead(Date))), unit = "days"), "days")/2)),
    .default = Date
  )) %>%
  mutate(Date = if_else(TypeEvent == "Breed" & ID == 12717 | ID == 22717, EndLoc, Date)) %>%
  mutate(Date = if_else(TypeEvent == "Birth" & ID == 12717 | ID == 22717, lead(Date) - years(1), Date),
    StartLoc = if_else(ID == 12717 | ID == 22717, EndLoc - years(1), StartLoc)) %>%
  mutate(Date = if_else(
    is.na(Date) & TypeEvent == "Transfer" & lead(TypeEvent) != "End",
    lag(Date) + days(floor(as.numeric(as.period((interval(lag(Date), lead(Date))), unit = "days"), "days")/2)),
    Date
  )) %>%
  mutate(Date = if_else(
    is.na(Date) & lag(TypeEvent) == "Birth" & is.na(lag(Date)),
    lead(Date) - years(1), Date
  )) %>%
  mutate(Date = case_when(
    is.na(Date) & TypeEvent == "Birth" ~ lead(Date) - years(1),
    is.na(Date) & TypeEvent == "End" & !(ID %in% alive) ~ lag(Date) + years(1),
    .default = Date)) %>%
  mutate(
    StartLoc = case_when(
      TypeEvent == "Breed" ~ lag(StartLoc),
      TypeEvent != "End" & TypeEvent != "Breed" ~ Date,
      TypeEvent == "End" & lag(TypeEvent) != "Breed" ~ lag(Date),
      .default = StartLoc
      ),
    EndLoc = case_when(
      TypeEvent == "Breed" & Location == lead(Location) ~ lead(EndLoc),
      lead(TypeEvent) == "Transfer" | lead(TypeEvent) == "End" ~ lead(Date),
      TypeEvent == "End" ~ Date,
      .default = EndLoc
      )
    ) %>% group_by(ID, Location) %>%
  fill(StartLoc, EndLoc, .direction = "updown") %>%
  ungroup()
```

```{r, warning = FALSE}
studbook.revised <- timeline %>%
  filter(TypeEvent != "Breed") %>%
  left_join(select(
    studbook,
    ID,
    Status,
    OrderLoc,
    Location,
    NameLoc,
    Country,
    Sex,
    Sire,
    Dam
  ), by = join_by(ID, OrderLoc, Location)) %>% distinct() %>%
  mutate(DateBirth = if_else(TypeEvent == "Birth", Date, NA)) %>%
  group_by(ID) %>% fill(DateBirth) %>% ungroup() %>%
  mutate(AgeStart = floor(as.numeric(as.period(interval(DateBirth, StartLoc), unit = "years"), "years")),
         AgeEnd   = floor(as.numeric(as.period(interval(DateBirth, EndLoc), unit = "years"), "years")))

write.table(studbook.revised, here(path$AZAstudbooks$working), sep = "\t", row.names = F)
```


```{r, warning = FALSE}
location.dates <- studbook.revised %>%
  select(
    ID,
    Sex,
    Location,
    DateBirth,
    StartLoc,
    EndLoc
  ) %>% distinct()

monthly.census <- pmap(
  list(
    pull(location.dates, StartLoc),
    pull(location.dates, EndLoc),
    pull(location.dates, DateBirth),
    pull(location.dates, Location),
    pull(location.dates, Sex),
    pull(location.dates, ID)
  ), generate_presence_list) %>%
  bind_rows() %>%
  group_by(Date, Location) %>%
  summarise(Individuals = list(
    tibble(ID, Sex, Age)), 
    .groups = "drop") %>%
  group_by(Date) %>%
  summarise(Locations = split(Individuals, 
                              Location), 
            .groups = "drop") %>%
  split(.$Date) %>%
  map(~ .x$Locations)
```

```{r}
find.sires <- whoisthedaddy(studbook.revised, monthly.census)
find.dams  <- whoisthemommy(studbook.revised, monthly.census)
```
