---
title: "Demographic Data Summaries for AZA Pygmy Loris Provisional SSP"
author: "Alicia Rich"
output:
  html_document:
    theme:
      bootswatch: litera
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    code_folding: "show"
    fig_caption: true
    df_print: paged
params:
  sampleset: "loris"
  dataset: "culi"
                     
---

```{r global, message = FALSE}
global             <- config::get(config = "default")

here::i_am("DemographicsLorises.Rmd")
source(here::here(global$setup))
```

```{r}
comments <- list(
  "ANALYTICAL DATA FOR TRUE INDIVIDUALS" = list(
    "2108" = list(
    "Field"   = "Sire",
    "TRUE"    = "UNK",
    "Overlay" = "HYP1",
    "Note"    = 
    "No individuals in the SB are recorded as having been at institution at which 2108 was born (IRCHEL) other than SB#s 2108 and 2097. Therefore, created and assigned a wild-origin hypothetical sire, which seems reasonable given the birth date of SB# 2108 and the origins of the recorded mother."),
  "2717" = list(
    "Field"   = c("Sire", "Dam"),
    "TRUE"    = "UNK",
    "Overlay" = c("HYP2", "HYP3"),
    "Note"    = 
    "This individual is possibly from the pet trade. No other animals from GREENWICH or VA SAFARI have previously entered the studbook, so the animal is unlikely to be related to any individuals currently in the population. Assumed to have wild (unrelated) origins.")
  )
)
```


```{r}
hypotheticals <- list(
    "12108" = list(
      "Sex"         = "M",
      "OffspringID" = 2108,
      "Location"    = "IRCHEL", 
      "Note"        = "To represent likely wild caught sire of SB# 2108, which was born at IRCHEL in Switzerland on 4/10/1989."
    ),
    "12717" = list(
      "Sex"         = "M",
      "OffspringID" = 2717,
      "Location"    = "GREENWICH",
      "Note"        = "Created to represent parents of 2717, which is likely unrelated to the rest of the population due to origin."),
    "22717" = list(
      "Sex"         = "F",
      "OffspringID" = 2717,
      "Location"    = "GREENWICH",
      "Note"        = "Created to represent parents of 2717, which is likely unrelated to the rest of the population due to origin.")
  ) %>%
  enframe(name = "ID") %>%
  unnest_wider(value) %>%
  mutate(Status    = "H",
         TypeEvent = "Birth",
         ID        = as.character(ID),
         IDnum     = as.integer(ID))

hyp.sires <- filter(hypotheticals, Sex == "M") %>% select(ID = OffspringID, HypSire = ID)
hyp.dams  <- filter(hypotheticals, Sex == "F") %>% select(ID = OffspringID, HypDam  = ID)
```

```{r}
locationsCurrent25 <- read.csv(here(path$AZAstudbooks$institutions$current25)) %>%
  select(Name    = Institution.Name, Label   = Mnemonic) %>%
  mutate(Country = "United States")

locationsCurrent21 <- read.csv(here(path$AZAstudbooks$institutions$current21)) %>%
  select(Name  = Institution.Name, Label = Mnemonic, Country)

locationsHistoric21 <- read.csv(here(path$AZAstudbooks$institutions$historic21)) %>%
  select(Name  = Institution.Name, Label = Mnemonic, Country) %>%
  add_row(Name = "Wild"     , Label = "VIETNAM"                     , Country = "Vietnam") %>%
  add_row(Name = "Wild"     , Label = "THAILAND"                    , Country = "Thailand") %>%
  add_row(Name = "Wild"     , Label = "LAOPEOPLESDEMOCRATICREPUBLIC", Country = "Laos") %>%
  add_row(Name = "SWITZRLND: Invalid use of GeoRef", 
          Label = "SWITZRLNDINVALIDUSEOFGEOREF", 
          Country = "Switzerland") %>%
  add_row(Name = "Wild"     , Label = "UNDETERMINED"                , Country = "Undetermined") %>%
  add_row(Name = "Wild"     , Label = "ASIA"                        , Country = "Undetermined") %>%
  add_row(Name = "Private Owner", Label = "GREENWICH"              , Country = "United Kingdom") %>%
  add_row(Name = "Virginia Safari Park", Label = "VASAFARI"              , Country = "United States")

locations <- bind_rows(locationsCurrent21, locationsHistoric21, locationsCurrent25) %>% 
  mutate(across(where(is.character), ~na_if(., "")),
         across(where(is.character), ~str_replace_all(., "\\n|\\t", " ")),
         across(where(is.character), ~str_trim(.))) %>%
  mutate(Label = if_else(is.na(Label), str_remove_all(Name, "(?<=.)(\\s\\w+){1,}"), Label)) %>%
  mutate(Label = str_remove_all(Label, "[^\\w+]")) %>%
  mutate(Label = str_to_upper(Label)) %>%
  distinct() %>%
  mutate(Abbrev  = as.character(str_sub(Label,  1L,  3L)),
         Abbrev2 = as.character(str_sub(Label, -2L, -1L))) %>%
  mutate(Abbrev = if_else(!is.na(lead(Abbrev)) & Abbrev == lead(Abbrev), 
                          str_replace(Abbrev, "(?<=^\\w)\\w{2}$", 
                                      Abbrev2), Abbrev), .keep = "unused") %>%
  arrange(Country, Name)


location.key <- sample(palettes_d$palettesForR$Cranes, 
                       size = length(unique(locations$Abbrev)), 
                       replace = FALSE) %>%
  as.list() %>%
  set_names(., map(as.list(unique(locations$Abbrev)), \(x) paste0(x))) %>%
  enframe(name = "Abbrev", value = "colorLoc")  %>% 
  mutate(colorLoc = as.character(colorLoc)) %>%
  right_join(locations, by = join_by(Abbrev)) %>%
  mutate(iconLoc = case_when(
    Country == "United States"             ~ "\U1F1FA\U1F1F8",
    Country == "United Kingdom"            ~ "\U1F1EC\U1F1E7",
    Country == "Vietnam"                   ~ "\U1F1FB\U1F1F3",
    Country == "Canada"                    ~ "\U1F1E8\U1F1E6",
    Country == "Denmark"                   ~ "\U1F1E9\U1F1F0",
    Country == "Germany"                   ~ "\U1F1E9\U1F1EA",
    Country == "Poland"                    ~ "\U1F1F5\U1F1F1",
    Country == "Russian Federation"        ~ "\U1F1F7\U1F1FA",
    Country == "Sweden"                    ~ "\U1F1F8\U1F1EA",
    Country == "Switzerland"               ~ "\U1F1E8\U1F1ED",
    Country == "Taiwan"                    ~ "\U1F1F9\U1F1FC",
    Country == "Thailand"                  ~ "\U1F1F9\U1F1ED",
    Country == "Laos"                      ~ "\U1F1F1\U1F1E6",
    Country == "Undetermined"              ~ "\U1F6A9",
    is.na(Country)                         ~ "\U1F6A9"
  ))

```



```{r}
living.25 <- read.csv(here(path$AZAstudbooks$living25)) %>%
  select(ID = Studbook.ID,
         Sex             = Sex.Type,
         Status          = Current.Status,
         Sire,
         Dam,
         TypeEvent       = Event.Type,
         Date,
         Location) %>%
  filter( str_detect(TypeEvent, "\\w+.+")) %>%
  mutate(Date = dmy(str_extract(Date, "\\d{1,2}/\\w{3}/\\d{2,4}")),
         across(c("Sire", "Dam"),   ~ as.character(.)),
         across(where(is.character), ~ na_if(., "")),
         across(c("Sex", "Status"), ~ str_sub(., 1L, 1L)),
         TypeEvent = fct_recode(str_to_title(TypeEvent), 
                           Capture  = "Wild Capture",
                           Birth    = "Birth/Hatch",
                           Transfer = "Transfer"  ,
                           LTF      = "Go Ltf"     ,
                           Death    = "Death" 
                           )
         ) %>%
  mutate(across(c("Sire", "Dam"),   ~ if_else(str_detect(., "^[^\\d+]"), NA, .))) %>%
  fill(ID) %>%
  group_by(ID) %>%
  fill(Sire, Dam, Sex, Status) %>%
  mutate(OrderEvent = paste0("l25_", row_number())) %>% ungroup()

alive       <- filter(living.25, Status == "A") %>% pull(ID) %>% unique()
current_pop <- pull(living.25, ID) %>% unique()

living.21 <- read.csv(here(path$AZAstudbooks$living21)) %>%
  select(ID = Studbook.ID,
         Sex             = Sex.Type,
         Sire,
         Dam,
         TypeEvent       = Event.Type,
         Date,
         Location) %>%
  filter( str_detect(TypeEvent, "\\w+.+")) %>%
  mutate(Date = dmy(str_extract(Date, "\\d{1,2}/\\w{3}/\\d{2,4}")),
         across(c("Sire", "Dam"),    ~ as.character(.)),
         across(where(is.character), ~ na_if(., "")),
         Sex = str_sub(Sex, 1L, 1L),
         TypeEvent = fct_recode(str_to_title(TypeEvent), 
                           Capture  = "Wild Capture",
                           Birth    = "Birth/Hatch",
                           Transfer = "Transfer"  ,
                           LTF      = "Go Ltf"     ,
                           Death    = "Death" 
                           )
         ) %>%
  mutate(across(c("Sire", "Dam"),   ~ if_else(str_detect(., "^[^\\d+]"), NA, .))) %>%
  fill(ID) %>%
  mutate(Status = if_else(ID %in% alive, "A", "D")) %>%
  group_by(ID) %>%
  fill(Sire, Dam, Sex) %>%
  mutate(OrderEvent = paste0("l21_", row_number())) %>% ungroup()

living <- bind_rows(living.21, living.25) %>%
  arrange(ID) %>%
  group_by(ID) %>%
  mutate(Sex = if_else(Sex == "U" & !is.na(lead(Sex)) & lead(Sex) != "U", lead(Sex), Sex))
```


```{r}
historic.21 <- read.csv(here(path$AZAstudbooks$historic21)) %>%
  select(ID              = Studbook.ID,
         Sex             = Sex.Type,
         Sire,
         Dam,
         DateBirth       = Birth.Date,
         TypeEvent       = Event.Type,
         Date,
         Location) %>%
  filter( str_detect(TypeEvent, "\\w+.+")) %>%
  mutate(across(c("Date", "DateBirth"),
                ~ dmy(str_extract(., "\\d{1,2}/\\w{3}/\\d{2,4}"))),
         across(c("Sire", "Dam"),    ~ as.character(.)),
         across(where(is.character), ~ na_if(., "")),
         Sex       = str_sub(Sex, 1L, 1L),
         TypeEvent = fct_recode(str_to_title(TypeEvent), 
                           Capture  = "Wild Capture",
                           Birth    = "Birth/Hatch",
                           Transfer = "Transfer"  ,
                           LTF      = "Go Ltf"     ,
                           Death    = "Death" 
                           )) %>%
  mutate(Location = str_to_upper(str_remove_all(Location, "[^\\w+]"))) %>%
  mutate(across(c("Sire", "Dam"),   ~ if_else(str_detect(., "^[^\\d+]"), NA, .))) %>%
  fill(ID) %>%
  mutate(Status = if_else(ID %in% alive, "A", "D")) %>%
  group_by(ID) %>%
  fill(Sire, Dam, Sex, Status, DateBirth) %>%
  mutate(Date       = if_else(is.na(Date) & !is.na(DateBirth) & TypeEvent == "Birth|Capture", DateBirth, Date),
         DateBirth  = if_else(is.na(DateBirth) & !is.na(Date) & TypeEvent == "Birth|Capture", Date, DateBirth),
         OrderEvent = paste0("h21_", row_number()))  %>%
  fill(DateBirth, .direction = "downup") %>% ungroup()
```


```{r}
studbook <- bind_rows(living, historic.21) %>% arrange(ID) %>% distinct() %>% 
  mutate(Location = na_if(Location, ""),
         Location = str_replace_all(Location, "\\n|\\t", " "),
         Location = str_trim(Location)) %>%
  mutate(Location = str_remove_all(Location, "[^\\w+]")) %>%
  mutate(Location = str_to_upper(Location)) %>%
  left_join(hyp.sires, by = join_by(ID)) %>%
  left_join(hyp.dams, by = join_by(ID)) %>%
  bind_rows(select(hypotheticals, 
                   Location ,
                   Status   ,
                   TypeEvent,
                   ID = IDnum,
                   Sex))  %>%
  mutate(Sire = if_else(!is.na(HypSire), HypSire, Sire),
         Dam  = if_else(!is.na(HypDam) , HypDam , Dam), .keep = "unused") %>%
  left_join(select(location.key, 
                   LocAbbrev = Abbrev, 
                   Label, 
                   colorLoc, 
                   NameLoc = Name, 
                   Country, 
                   iconLoc), 
            by = join_by(Location == Label)) %>%
  mutate(Location = LocAbbrev, .keep = "unused") %>%
  mutate(TypeEvent = fct(TypeEvent, levels = c("Capture", "Birth", "Transfer", "LTF", "Death"))) %>%
  group_by(ID) %>%
  mutate(Order = row_number()) %>% relocate(Order, .after = TypeEvent)
```


```{r}
location.orders <- select(studbook, ID, Order, Location, TypeEvent, Date) %>%
  arrange(ID, Order) %>%
  filter(TypeEvent == "Transfer") %>%
  group_by(ID) %>%
  mutate(LocOrder = row_number()) %>% ungroup %>% select(-Order)

deceased <- filter(studbook, Status == "D" | Status == "H") %>% pull(ID) %>% unique()
N_records <- sum(length(deceased), length(alive))
print(N_records)
```

```{r}
births <- filter(studbook, TypeEvent == "Birth" | TypeEvent == "Capture") %>%
  select(ID, Sex, Sire, Dam, DateBirth, TypeEvent, Date, Location) %>%
  distinct() %>%
  pivot_wider(
    id_cols = c(
      "ID",
      "Sex",
      "Sire",
      "Dam",
      "DateBirth"
    ),
    names_from  = "TypeEvent",
    names_sep   = "_",
    values_from = c("Date", "Location")
  ) %>%
  mutate(
  Date = case_when(
    is.na(DateBirth) & is.na(Date_Capture) & !is.na(Date_Birth) ~ Date_Birth,
    is.na(DateBirth) & !is.na(Date_Capture) & is.na(Date_Birth) ~ Date_Capture,
    !is.na(DateBirth) ~ DateBirth
  ),
  Location = case_when(
    is.na(Location_Birth) & !is.na(Location_Capture) ~ Location_Capture,
    !is.na(Location_Birth) ~ Location_Birth
  ),
  TypeEvent = "Birth",
  Order     = 1,
  From      = "Birth",
  .keep = "unused") %>% distinct()  %>%
  group_by(ID) %>%
  arrange(ID, desc(Sex)) %>%
  mutate(Sex = if_else(Sex == "U" & !is.na(lead(Sex)) & lead(Sex) != "U", lead(Sex), Sex)) %>%
  ungroup() %>% distinct() %>%
  left_join(select(living.25, ID, Sex_revised = Sex), by = join_by(ID)) %>%
  mutate(Sex = if_else(!is.na(Sex_revised) & Sex != Sex_revised, Sex_revised, Sex), .keep = "unused") %>% 
  distinct() %>% left_join(select(studbook, -c(Sex, Sire, Dam, Date, Location, Order, OrderEvent, DateBirth)), 
                           by = join_by(ID, TypeEvent)) %>% distinct() %>% mutate(DateBirth = Date)

duplicates <- births %>% filter(ID == lead(ID) | ID == lag(ID))
```


```{r}
breeding <- select(births,
                   OffspringID = ID,
                   Sire,
                   Dam,
                   Date,
                   Location) %>%
  pivot_longer(cols      = c("Sire", "Dam"),
               names_to  = "Sex",
               values_to = "ID") %>%
  mutate(Sex       = if_else(Sex == "Sire", "M", "F"),
         TypeEvent = "Breed", ID = as.integer(ID)) %>%
  relocate(ID) %>%
  filter(!is.na(ID)) %>% distinct() %>%
  left_join(select(studbook, -c(Sex, Date, TypeEvent, OrderEvent)), 
                           by = join_by(ID, Location)) %>% 
  group_by(ID) %>% arrange(ID, Location, Date) %>%
  fill(DateBirth, .direction = "downup") %>%
  ungroup() %>% select(-Order) %>%
  distinct() %>%
  group_by(ID, Location) %>%
  mutate(OrderBreed = row_number()) %>%  
  distinct() %>% 
  ungroup()
```

```{r}
deaths.v1 <- filter(studbook, TypeEvent == "Death" | TypeEvent == "LTF") %>%
  select(ID, TypeEvent, Date, Location, Status) %>%
  distinct() %>%
  pivot_wider(
    id_cols     = c("ID", "Status"),
    names_from  = "TypeEvent",
    names_sep   = "_",
    values_from = c("Date", "Location")
  ) %>%
  mutate(
  TypeEvent = case_when(
    is.na(Date_Death) ~ "LTF",
    !is.na(Date_Death) ~ "Death"
  ),
  Date = case_when(
    is.na(Date_Death) & !is.na(Date_LTF) ~ Date_LTF,
    is.na(Date_LTF) & !is.na(Date_Death) ~ Date_Death
  ),
  Location = case_when(
    is.na(Location_Death) & !is.na(Location_LTF) ~ Location_LTF,
    is.na(Location_LTF) & !is.na(Location_Death) ~ Location_Death
  ),
  .keep = "unused") %>% distinct()

GoLTFs <- filter(studbook, ID %in% setdiff(deceased, pull(deaths.v1, ID))) %>%
  select(ID, TypeEvent, Date, Location, Status) %>%
  group_by(ID) %>%
  slice_max(order_by = Date, n = 1) %>%
  mutate(TypeEvent = "LTF") %>%
  ungroup() %>%
  select(ID, TypeEvent, Location, Status) %>% distinct()

deaths <- deaths.v1 %>% bind_rows(GoLTFs) %>% arrange(ID) %>% 
  left_join(select(studbook, -c(Date, Location, OrderEvent, DateBirth)), 
                           by = join_by(ID, TypeEvent, Status)) %>% distinct() %>% 
  mutate(DateDeath = Date)
  

duplicates <- deaths %>% filter(ID == lead(ID) | ID == lag(ID))

```

```{r}
studbook.v2 <- filter(studbook, TypeEvent == "Transfer") %>%
  bind_rows(births) %>%
  bind_rows(deaths) %>%
  mutate(TypeEvent = fct(TypeEvent, levels = c("Birth", "Transfer", "LTF", "Death"))) %>%
  arrange(ID, TypeEvent, Date) %>%
  group_by(ID) %>%
  mutate(Order = row_number()) %>%
  select(
    ID,
    Status,
    Sex,
    Sire,
    Dam,
    Location,
    TypeEvent,
    Order,
    Date,
    DateBirth,
    DateDeath,
    colorLoc,
    NameLoc,
    Country,
    iconLoc
  )  %>%
  fill(Sex, Sire, Dam, DateBirth, DateDeath, .direction = "downup") %>% ungroup()

transfers <- studbook.v2 %>% 
  arrange(ID, Order) %>%
  group_by(ID) %>%
  mutate(From = lag(Location)) %>%
  filter(TypeEvent == "Transfer" | TypeEvent == "Birth") %>%
  select(ID, TypeEvent, Date, From, To = Location) %>%
  mutate(LocOrder = row_number()) %>%
  ungroup() %>% filter(TypeEvent == "Transfer") %>%
  distinct()

repro.events <- breeding %>%
  select(ID, OrderBreed, Date, To = Location, TypeEvent) %>%
  mutate(From = To) %>% distinct() %>% arrange(ID, Date, OrderBreed)

end.records <- deaths %>%
  select(ID, Date, From = Location, TypeEvent) %>%
  mutate(To = "End") %>% distinct() %>% arrange(ID)
```

```{r}
records <- select(births,
                  ID,
                  TypeEvent,
                  Order,
                  Date,
                  From,
                  To = Location,
                  Status) %>%
  arrange(ID, Order) %>%
  mutate(LocOrder = 1) %>%
  bind_rows(transfers) %>%
  arrange(ID, LocOrder) %>%
  bind_rows(repro.events) %>%
  mutate(TypeEvent = fct(TypeEvent, levels = c("Birth", "Transfer", "Breed", "End"))) %>%
  arrange(ID, LocOrder, TypeEvent, OrderBreed) %>%
  relocate(LocOrder, OrderBreed, .after = Order) %>%
  group_by(ID) %>% fill(Status) %>% 
  mutate(Status = replace_na(Status, "A"),
         Order  = row_number())


gaps <- filter(records, !is.na(Date)) %>%
  group_by(ID) %>%
  mutate(Lag  = int_length(interval(lag(Date), Date)),
         Lead = int_length(interval(Date, lead(Date))))
```


  mutate(Date = if_else(
    is.na(Date) & Order == 1, lead(Date) - months(2), Date
    ))
```{r}
records <- studbook.v2 %>%
  filter(TypeEvent == "Birth") %>%
  select(ID, Date, To = Location, TypeEvent) %>%
  mutate(From = "Birth", TransOrder = 1) %>%
  bind_rows(transfers) %>%
  arrange(ID, TransOrder) %>%
  group_by(ID) %>%
  mutate(TransOrder = case_when(
    is.na(TransOrder), lag(TransOrder) + 1, TransOrder)) %>%
  mutate(From = if_else(is.na(From), lag(To), From)) %>%
  select(ID, TransOrder, TypeEvent, Date, From, To) %>%
  bind_rows(repro.events) %>%
  arrange(ID, To, Date) %>%
  fill(TransOrder) %>%
  ungroup() %>%
  group_by(ID, To) %>%
  mutate(LocOrder = row_number())
  
```


```{r}
 %>%
  arrange(ID, Order, Date) %>%
  mutate(Order = row_number()) %>%
  bind_rows(end.records) %>%
  arrange(ID, Order, Date) %>%
  mutate(Order = if_else(TypeEvent == "LTF" | TypeEvent == "Death", lag(Order) + 1, Order))  %>%
  mutate(TypeEvent = if_else(TypeEvent == "Death" | TypeEvent == "LTF", "End", TypeEvent))  %>%
  mutate(From = if_else(
    From == "UND" & TypeEvent == "End" & lag(To) != "UND", lag(To), From),
    To = if_else(To == "UND" & TypeEvent == "End" & lag(To) != "UND", lag(To), To)) %>%
  mutate(Date = if_else(is.na(Date) & TypeEvent == "End"  , lag(Date) + months(2), Date)) %>%
  mutate(Date = if_else(is.na(Date) & TypeEvent == "Birth", lead(Date) - months(2), Date))
```



```{r}
records <- births %>%
  select(ID, Date, To = Location, TypeEvent) %>%
  mutate(From = "Birth", Order = 1) %>%
  bind_rows(transfers) %>%
  arrange(ID, Order) %>%
  group_by(ID) %>%
  mutate(From = if_else(is.na(From), lag(To), From)) %>%
  select(ID, Order, TypeEvent, Date, From, To) %>%
  bind_rows(repro.events) %>%
  arrange(ID, Date) %>%
  group_by(ID) %>%
  mutate(Order = if_else(is.na(Order), lag(Order) + 1, Order)) %>%
  arrange(ID, Order, Date) %>%
  mutate(Order = row_number()) %>%
  bind_rows(end.records) %>%
  arrange(ID, Order, Date) %>%
  mutate(Order = if_else(TypeEvent == "LTF" | TypeEvent == "Death", lag(Order) + 1, Order)) %>%
  mutate(DateEst = if_else(is.na(Date), "Y", "N")) %>%
  mutate(Date = case_when(
    is.na(Date) & TypeEvent == "Birth"                       ~ lead(Date) - months(2),
    is.na(Date) & TypeEvent == "LTF" | TypeEvent == "Death"  ~ lag(Date) + months(2),
    is.na(Date) & TypeEvent == "Transfer" & is.na(lag(Date)) ~ lead(Date) - months(2),
    is.na(Date) & TypeEvent == "Transfer" & is.na(lead(Date)) ~ lag(Date) + months(2),
    is.na(Date) & TypeEvent == "Transfer" & !is.na(lead(Date)) & !is.na(lag(Date)) ~ 
     lag(Date) + (lead(Date) - lag(Date)) / 2,
    .default = Date
  )) %>%
  mutate(Date = case_when(
    is.na(Date) & TypeEvent == "Birth"                       ~ lead(Date) - months(2),
    is.na(Date) & TypeEvent == "LTF" | TypeEvent == "Death"  ~ lag(Date) + months(2),
    is.na(Date) & TypeEvent == "Transfer" & is.na(lag(Date)) ~ lead(Date) - months(2),
    is.na(Date) & TypeEvent == "Transfer" & is.na(lead(Date)) ~ lag(Date) + months(2),
    is.na(Date) & TypeEvent == "Transfer" & !is.na(lead(Date)) & !is.na(lag(Date)) ~ 
     lag(Date) + (lead(Date) - lag(Date)) / 2,
    .default = Date
  )) %>%
  ungroup()
```


```{r}
studbook.working <- records %>%
  filter(TypeEvent == "Birth" | TypeEvent == "End") %>%
  rename(Location = To) %>%
  pivot_wider(id_cols     = ID,
              names_from  = TypeEvent,
              names_sep   = "_",
              values_from = c("Date", "Location")) %>%
  right_join(filter(records, TypeEvent != "Birth" & TypeEvent != "End"), by = join_by(ID)) %>%
  select(
    ID, 
    DateBirth = Date_Birth, 
    LocBirth  = Location_Birth, 
    DateLast  = Date_End, 
    LocLast   = Location_End, 
    TypeEvent,
    DateEvent = Date, 
    DateEst, 
    LocEvent  = To
  ) %>%
  left_join(select(births,
                   ID,
                   Sex,
                   Sire,
                   Dam,
                   Status), by = join_by(ID)) %>%
  left_join(select(breeding,
                   ID,
                   OffspringID,
                   Date,
                   Location,
                   TypeEvent), by = join_by(ID, 
                                            DateEvent == Date, 
                                            LocEvent  == Location, 
                                            TypeEvent)) %>%
  left_join(select(filter(records, TypeEvent == "Birth"),
                   OffspringID = ID,
                   DateBreed = Date), by = join_by(OffspringID)) %>%
  mutate(DateEvent = if_else(is.na(DateEvent) & TypeEvent == "Breed", DateBreed, DateEvent)) %>%
  select(-DateBreed) %>%
  mutate(DateLast  = if_else(is.na(DateLast ) & Status == "H", DateEvent, DateLast),
         DateBirth = if_else(is.na(DateBirth) & Status == "H", DateEvent - years(2), DateBirth)) %>%
  group_by(ID) %>%
  mutate(EventOrder = row_number()) %>%
  relocate(EventOrder, .before = TypeEvent) %>%
  mutate(LocLast = if_else(is.na(LocLast) & EventOrder == max(EventOrder), LocEvent, LocLast)) %>%
  fill(LocLast, .direction = "up") %>%
  mutate(DateLast = if_else(ID %in% alive, today(), DateLast)) %>%
  left_join(select(location.key, 
                   IconBirth  = iconLoc, 
                   ColorBirth = colorLoc, 
                   LocBirth   = Abbrev), 
      by = join_by(LocBirth)) %>%
  left_join(select(location.key, 
                   IconLocEvent  = iconLoc, 
                   ColorLocEvent = colorLoc, 
                   LocEvent      = Abbrev), 
      by = join_by(LocEvent)) %>%
  left_join(select(location.key, 
                   IconLocLast   = iconLoc, 
                   ColorLocLast  = colorLoc, 
                   LocLastName   = Name,
                   LocLast       = Abbrev), 
      by = join_by(LocLast)) %>%
  ungroup() %>% distinct()

write.table(studbook.working, here(path$AZAstudbooks$working), sep = "\t", row.names = F)
```

```{r}
timeline.locs <- select(studbook.working, 
                      ID,
                      Start    = DateBirth,
                      Location = LocBirth) %>%
               bind_rows(
                 select(filter(studbook.working, TypeEvent == "Transfer"), 
                        ID,
                        Start    = DateEvent,
                        Location = LocEvent)
                 ) %>%
               left_join(
                 select(studbook.working,
                        ID,
                        DateLast), by = join_by(ID)
               ) %>%
               distinct() %>%
               group_by(ID) %>%
               arrange(ID, Start) %>%
               mutate(Order = row_number()) %>%
               mutate(End   = if_else(Order == max(Order), DateLast, lead(Start))) %>%
               ungroup() %>% select(
                 ID,
                 Location,
                 Start,
                 End
               ) %>%
               distinct()

write.table(timeline.locs, here(path$AZAstudbooks$timeline), sep = "\t", row.names = F)

```

```{r}
LocStarts <- timeline.locs %>%
  select(Location, Start) %>%
  group_by(Location) %>%
  slice_min(order_by = Start, n = 1) %>%
  ungroup() %>% distinct()

LocEnds <- timeline.locs %>%
  select(Location, End) %>%
  group_by(Location) %>%
  slice_max(order_by = End, n = 1) %>%
  ungroup() %>% distinct()

LocIntervals <- LocStarts %>% 
  left_join(LocEnds, by = join_by(Location)) %>%
  mutate(across(c("Start", "End"), ~ floor_date(., "months"))) %>%
  arrange(Start, End)
```


```{r}
minMonth <- floor_date(min(pull(timeline.locs, Start)), "month")
maxMonth <- floor_date(today(), "month")

Monthly <- as.list(seq(minMonth, maxMonth, by = "months")) %>%
  pmap(as.list())

```


```{r}
Monthly <- timeline.locs %>%
  mutate(month = map2(Start, End, ~ seq(from = floor_date(.x, "month"),
                                        to   = floor_date(.y, "month"),
                                        by   = "months"))) %>%
  unnest(month)

census <- Monthly %>%
  group_by(month, Location) %>%
  summarise(IDs = list(unique(ID)), .groups = "drop") %>%
  nest(data     = c(Location, IDs))

```




