---
title: "Demographic Data Summaries for AZA Pygmy Loris Provisional SSP"
author: "Alicia Rich"
output:
  html_document:
    theme:
      bootswatch: litera
      css: "Studbook.css"
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    code_folding: "show"
    fig_caption: true
    df_print: paged
params:
  sampleset: "loris"
  dataset: "culi"
                     
---

```{r global, message = FALSE, warning = FALSE}
global             <- config::get(config = "default")

here::i_am("Demography.Rmd")
source(here::here(global$setup))

source(here(path$AZAstudbooks$functions))
source(here(path$AZAstudbooks$btp))

source(here(path$AZAstudbooks$load_data))
source(here(path$AZAstudbooks$reactables))

opts_chunk$set(message = FALSE,
               warning = FALSE,
               echo    = TRUE,
               include = TRUE,
               eval    = TRUE,
               comment = "")

subjects <- list(culi = 2652, warble = 2677)

```

# Fill in Studbook Data

```{r, warning = FALSE}
timeline <- assemble_timeline(studbook) %>% fill_dates_timeline()

studbook <- revise_studbook(studbook, timeline)
```

## Fill Missing Parentage Assignments

```{r, warning = FALSE}
locate.parents <- expand_timeline(timeline, "months", studbook) %>%
  arrange(Sex, BirthYear) %>%
  nest_timeline(., groupBy = "Location")

find.sires <- whoisthedaddy(studbook, locate.parents)
find.dams  <- whoisthemommy(studbook, locate.parents)
```

## Create Hypothetical IDs and Add Missing Parents

```{r}
final.studbook <- studbook %>%
  mutate(Sire = case_match(ID, 
                           1047 ~ 1012, 
                           2645 ~ 1131, 
                           2738 ~ 2622, .default = Sire)) %>%
  mutate(Dam  = if_else(ID == 2738, 2630, Dam)) %>%
  add.hypotheticals(c(1045, 1046), "Sire") %>%
  add.hypotheticals(c(2423, 2424), "Sire") %>%
  add.hypotheticals(c(2108), "Sire") %>%
  add.hypotheticals(c(2717), "Dam") %>%
  add.hypotheticals(c(2717), "Sire")

write.table(final.studbook, here(path$AZAstudbooks$working), sep = "\t", row.names = F)

timeline.revised <- update_timeline(timeline, studbook, final.studbook)
studtbl          <- studbook_visual(timeline.revised, final.studbook, locations)
```

```{r}

```


# Summary Statistics

```{r}
life.table.sexes <- count_births(timeline.revised, final.studbook) %>%
      summarize(Births = sum(Births),
                Nx     = n(), 
                .by    = c(BirthYear, Sex, Age)
                ) %>%
      ungroup() %>%
  make_cohorts(., 1985, 2024, 10, 22, TRUE) %>%
  summarize(Births = sum(Births),
           Nx      = sum(Nx), 
           .by     = c(CohortLabel, BirthCohort, Sex, Cohort, Age)) %>%
  arrange(BirthCohort, Sex, Age) %>%
  lifeTab()

lifeTab.decades <- count_births(timeline.revised, final.studbook) %>%
      summarize(Births = sum(Births),
                Nx     = n(), 
                .by    = c(BirthYear, Age)
                ) %>%
      ungroup() %>%
  make_cohorts(., 1985, 2024, 10, 22, FALSE) %>%
  summarize(Births = sum(Births),
           Nx      = sum(Nx), 
           .by     = c(CohortLabel, BirthCohort, Cohort, Sex, Age)) %>%
  arrange(BirthCohort, Age) %>%
  lifeTab() %>%
  bind_rows(life.table.sexes) %>%
  arrange(BirthCohort, Age, Sex)

write.table(life.table, here(path$AZAstudbooks$lifetable), sep = "\t", row.names = F)
```

```{r}
life.table.sexes <- count_births(timeline.revised, final.studbook) %>%
      summarize(Births = sum(Births),
                Nx     = n(), 
                .by    = c(BirthYear, Sex, Age)
                ) %>%
      ungroup() %>%
  make_cohorts(., 1985, 2024, 5, 22, TRUE) %>%
  summarize(Births = sum(Births),
           Nx      = sum(Nx), 
           .by     = c(CohortLabel, BirthCohort, Sex, Cohort, Age)) %>%
  arrange(BirthCohort, Sex, Age) %>%
  lifeTab()

lifeTab.5yrs <- count_births(timeline.revised, final.studbook) %>%
      summarize(Births = sum(Births),
                Nx     = n(), 
                .by    = c(BirthYear, Age)
                ) %>%
      ungroup() %>%
  make_cohorts(., 1985, 2024, 5, 22, FALSE) %>%
  summarize(Births = sum(Births),
           Nx      = sum(Nx), 
           .by     = c(CohortLabel, BirthCohort, Cohort, Sex, Age)) %>%
  arrange(BirthCohort, Age) %>%
  lifeTab() %>%
  bind_rows(life.table.sexes) %>%
  arrange(BirthCohort, Age, Sex)

```

```{r}
lifeTab.static <- lifeTab_static(lifeTab.5yrs) %>%
  annotate_lambda()
```




## Visuals

```{r}
col.pal <- keep_at(colors, c("f", "m", "u")) %>% unlist()
col.pal <- setNames(col.pal, c("F", "M", "Total"))
fills   <- gsub("FF", "33", col.pal)

```

```{r}
repro.plot <- plot_ly(
    data        = filter(lifeTab.static, Sex != "Total"),
    type        = "scatter",
    x           = ~CohortLabel,
    y           = ~R0,
    color       = ~Sex,
    colors      = col.pal,
    name        = "Reproductive Rate (R0) by Sex",
    text        = ~hover_lambda,
    mode        = "lines+markers",
    connectgaps = TRUE,
    line        = list(
      shape     = "spline",
      color     = ~Sex,
      colors    = col.pal,
      width     = 1.5
      ),
    marker      = list(
      fill      = ~Sex,
      colors    = fills,
      size      = 6,
      opacity   = 0.7,
      line      = list(
      color     = ~Sex,
      colors    = col.pal,
      width     = 1.0
        )
   )) %>%
  add_trace(
    data        = filter(lifeTab.static, Sex == "Total"),
    x           = ~CohortLabel,
    y           = ~Qx1,
    color       = "#90A4AEFF",
    name        = "Infant Mortality (Qx1)",
    mode        = "lines+markers",
    connectgaps = TRUE,
    line        = list(
      dash      = "dot",
      shape     = "spline",
    color       = "#90A4AEFF",
      width     = 1.5
      ),
    marker      = list(
      fill      = ~Sex,
      colors    = fills,
      size      = 3,
      opacity   = 0.3,
      line      = list(
      color     = "#90A4AEFF",
      width     = 0.5
        )
   )
    
  ) %>%
  layout(title        = "Pygmy Loris Reproductive Trends 1985-2024",
         plot_bgcolor = "#ffffff", 
         yaxis = list(title         = "Rate",
                      showline      = T,
                      zerolinewidth = 2,
                      zerolinecolor = "black",
                      showgrid      = F),
         xaxis = list(title         = "Birth Cohort",
                      showline      = T,
                      zerolinewidth = 2,
                      zerolinecolor = "black",
                      showgrid      = T))

repro.plot
```


```{r}
lambda.plot <- plot_ly(
    data        = filter(lifeTab.static, Sex != "Total"),
    type        = "scatter",
    x           = ~CohortLabel,
    y           = ~lambda,
    color       = ~Sex,
    colors      = col.pal,
    text        = ~hover_lambda,
    mode        = "lines+markers",
    connectgaps = TRUE,
    line        = list(
      shape     = "spline",
      color     = ~Sex,
      colors    = col.pal,
      width     = 1.5
      ),
    marker      = list(
      fill      = ~Sex,
      colors    = fills,
      size      = 6,
      opacity   = 0.7,
      line      = list(
      color     = ~Sex,
      colors    = col.pal,
      width     = 1.0
        )
   )) %>%
  layout(title        = "Pygmy Loris Population Growth 1985-2024",
         plot_bgcolor = "#ffffff", 
         shapes       = list(hline(1.0)),
         annotations  = lambda.annotation,
         yaxis = list(title         = "Lambda (\u03BB)",
                      showline      = T,
                      zerolinewidth = 2,
                      zerolinecolor = "black",
                      showgrid      = F),
         xaxis = list(title         = "Birth Cohort",
                      showline      = T,
                      zerolinewidth = 2,
                      zerolinecolor = "black",
                      showgrid      = T))

saveWidget(lambda.plot, paste0(path$visuals$demographics, "/Lambda_Cohorts.html"))
lambda.plot
```



```{r}
r0.plot <- plot_ly(
    data        = filter(lifeTab.static, Sex != "Total"),
    type        = "scatter",
    x           = ~CohortLabel,
    y           = ~R0,
    color       = ~Sex,
    colors      = col.pal,
    text        = ~hover_lambda,
    mode        = "lines+markers",
    connectgaps = TRUE,
    line        = list(
      shape     = "spline",
      color     = ~Sex,
      colors    = col.pal,
      width     = 1.5
      ),
    marker      = list(
      fill      = ~Sex,
      colors    = fills,
      size      = 6,
      opacity   = 0.7,
      line      = list(
      color     = ~Sex,
      colors    = col.pal,
      width     = 1.0
        )
   )) %>%
  layout(title        = "Pygmy Loris Reproductive Rates 1985-2024",
         plot_bgcolor = "#ffffff", 
         barmode      = "grouped",
         yaxis = list(title         = "Reproductive Rate (R0)",
                      showline      = T,
                      showgrid      = F),
         xaxis = list(title         = "Birth Cohort",
                      showline      = T,
                      showgrid      = T))



saveWidget(r0.plot, paste0(path$visuals$demographics, "/R0_Cohorts.html"))
r0.plot

```

```{r}
qx1.plot <- plot_ly(
    data        = filter(lifeTab.static, Sex != "Total"),
    type        = "scatter",
    x           = ~CohortLabel,
    y           = ~Qx1,
    color       = ~Sex,
    colors      = col.pal,
    text        = ~hover_lambda,
    mode        = "lines+markers",
    connectgaps = TRUE,
    line        = list(
      shape     = "spline",
      color     = ~Sex,
      colors    = col.pal,
      width     = 1.5
      ),
    marker      = list(
      fill      = ~Sex,
      colors    = fills,
      size      = 6,
      opacity   = 0.7,
      line      = list(
      color     = ~Sex,
      colors    = col.pal,
      width     = 1.0
        )
   )) %>%
  layout(title        = "Pygmy Loris Infant Mortality 1985-2024",
         plot_bgcolor = "#ffffff", 
         barmode      = "grouped",
         yaxis = list(title         = "Infant Mortality Rate (Qx1)",
                      showline      = T,
                      showgrid      = F),
         xaxis = list(title         = "Birth Cohort",
                      showline      = T,
                      showgrid      = T))



saveWidget(qx1.plot, paste0(path$visuals$demographics, "/Qx1_Cohorts.html"))
qx1.plot

```


```{r}
mle.t.plot <- plot_ly(
  data          = filter(lifeTab.static, Sex != "Total"),
  type          = "scatter",
    color       = ~Sex,
    colors      = col.pal,
    mode        = "lines+markers",
    connectgaps = TRUE
  ) %>%
  add_trace(
    x           = ~CohortLabel,
    y           = ~MLE,
    inherit     = TRUE,
    name        = "Median Life Expectancy (MLE)",
    line        = list(
      shape     = "spline",
      width     = 1.5
      ),
    marker      = list(
      fill      = ~Sex,
      colors    = fills,
      size      = 6,
      opacity   = 0.7,
      line      = list(
      width     = 1.0
      ))
    ) %>%
  add_trace(
    x           = ~CohortLabel,
    y           = ~T,
    inherit     = TRUE,
    name        = "Mean Generation Time (T)",
    line        = list(
      dash      = "dot",
      shape     = "spline",
      width     = 1.5
      ),
    marker      = list(
      fill      = ~Sex,
      colors    = fills,
      symbol    = "square",
      size      = 6,
      opacity   = 0.7,
      line      = list(
      width     = 1.0
      ))
    ) %>%
  layout(title        = "Pygmy Loris Life History 1985-2024",
         plot_bgcolor = "#ffffff", 
         yaxis = list(title         = "Years",
                      showline      = T,
                      showgrid      = F),
         xaxis = list(title         = "Birth Cohort",
                      showline      = T,
                      showgrid      = T)
         )

mle.t.plot
  
```


```{r}
fills           <- map_depth(colors, 1, \(x) gsub("FF", "12", x))

repro.plot <- plot_ly(
  data          = filter(lifeTab.static, Sex == "Total"),
  type          = "scatter",
    mode        = "lines",
    connectgaps = TRUE
  ) %>%
  add_trace(
    x             = ~CohortLabel,
    y             = ~MaxLongev,
    name          = "Maximum Longevity",
    showlegend    = TRUE,
    line          = list(
      dash        = "dot",
      color       = "#444444",
      shape       = "spline",
      width       = 0.5,
      showlegend  = FALSE
      )) %>%
  add_trace(
    x             = ~CohortLabel,
    y             = ~MLE,
    name          = "Median Life Expectancy",
    fill          = "tonexty",
    fillcolor     = "#eeeeee",
    line          = list(
      shape     = "spline",
      color     = "#444444",
      width     = 2
      ),
    marker      = list(
      fillcolor = "#44444444",
      size      = 8,
      opacity   = 0.8,
      line      = list(
      color     = "#444444",
      width     = 1
      ))
    ) %>%
  add_trace(
    x             = ~CohortLabel,
    y             = ~FirstRepro,
    name          = "Age at First Birth",
      showlegend  = TRUE,
    line          = list(
      dash        = "dot",
      color       = colors$u,
      shape       = "spline",
      width       = 0.8,
      showlegend  = FALSE
      )
    ) %>%
  add_trace(
    x             = ~CohortLabel,
    y             = ~T,
    name          = "Mean Generation Time (T)",
    fill          = "tonexty",
    fillcolor     = fills$u,
    line          = list(
      shape     = "spline",
      color     = colors$u,
      width     = 2.5
      ),
    marker      = list(
      fillcolor = fills$u,
      size      = 8,
      opacity   = 0.7,
      line      = list(
      color     = "black",
      width     = 1.5
      ))
    ) %>%
  add_trace(
    x             = ~CohortLabel,
    y             = ~LastRepro,
    name          = "Age at Last Birth",
      showlegend  = TRUE,
    fill          = "tonexty",
    fillcolor     = fills$u,
    line          = list(
      dash        = "dot",
      color       = colors$u,
      shape       = "spline",
      width       = 0.8,
      showlegend  = FALSE
      )
    ) %>%
  layout(plot_bgcolor = "#ffffff", 
         yaxis = list(title         = "Years",
                      showline      = T,
                      showgrid      = F),
         xaxis = list(title         = "Birth Cohort",
                      showgrid      = T
                      )
         )

repro.plot
  
```


```{r}
decade.cols <- c(
  "A" = "#CFD8DCFF", 
  "B" = "#90A4AEFF", 
  "D" = "#607D8BFF")

c("#E4E4E4FF", "#CBCBD6FF", "#B3B2C9FF", "#9A9ABCFF", "#8281AFFF", "#6968A2FF", "#515095FF", "#383788FF", "#201F7BFF")
```


```{r}

col.pal     <- c("#E4E4E4FF", "#CBCBD6FF", "#B3B2C9FF", "#201F7BFF")

decade.cols <- setNames(col.pal, c("A", "B", "D", "C"))

lx1.plot <- plot_ly(
  data          = filter(lifeTab.decades, Sex == "Total"),
  type          = "scatter",
  mode          = "lines+markers",
    color = ~BirthCohort,
    colors = decade.cols,
  connectgaps   = TRUE
                   ) %>%
  add_trace(
    data = filter(lifeTab.decades, Sex == "Total" & BirthCohort != "C"),
    x    = ~Age,
    y    = ~Lx1,
    name = ~CohortLabel,
    line          = list(
      dash      = "dot",
      shape     = "spline",
      width     = 1.5
      ),
    marker      = list(
      size      = 2,
      opacity   = 0.5,
      line      = list(
      width     = 0.8
      )
    )
  ) %>%
  add_trace(
    data = filter(lifeTab.decades, Sex == "Total" & BirthCohort == "C"),
    x    = ~Age,
    y    = ~Lx1,
    name = ~CohortLabel,
    line          = list(
      shape     = "spline",
      width     = 2
      ),
    marker      = list(
    color = ~BirthCohort,
    colors = decade.cols,
      size      = 8,
      opacity   = 0.8,
      line      = list(
      width     = 1
      ))
  ) %>%
  layout(plot_bgcolor = "#ffffff", 
         yaxis = list(title         = "Survivorship (Lx1)",
                      showgrid      = F),
         xaxis = list(title         = "Age Class (years)",
                      showgrid      = F
                      )
         )

lx1.plot
```


