---
title: "Loris Microbiome Project Results Overview"
author: "Alicia Rich"
output:
  html_document:
    theme:
      bootswatch: litera
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    code_folding: "show"
    fig_caption: true
    df_print: paged
params:
  sampleset: "loris"
                     
---

```{r, include = F}
global             <- config::get(config = "default")

here::i_am("MicroEcoDataPrep.Rmd")
source(here::here(global$setup))

for (file in swan$swan_scripts) {
  source(here(file))
}
for (file in micro$micro_scripts) {
  source(here(file))
}

source(here(path$metadata$key))
source(here(path$metadata$factors))


theme_set(theme_classic())
thematic_rmd()
thematic_on(accent = "#8785B2FF", fg = "black")
```

# Read in Data

I have written several custom functions to expedite some of the functions that I reuse multiple times for data sets across different sample and taxon subsets. The loop below will use one of those functions to read the microeco datasets that I built using the [MicroEcoDataPrep](MicroEcoDataPrep.html) script.

```{r}
# Define taxonomic and functional dataset categories
dataset_types <- c("tax", "function")
tax_levels <- c("spe", "gen", "fam", "ord", "cla", "phy")
func_levels <- c("keg", "fpt", "njc")
dataset_suffixes <- c("main", "culi", "warb")

# Create an empty list to store all datasets
microtable_datasets <- list()

# Loop through dataset types (taxonomic and functional)
for (data_type in dataset_types) {
  # Select appropriate levels based on type
  levels <- if (data_type == "tax") tax_levels else func_levels
  
  # Loop through levels and suffixes
  for (prefix in levels) {
    for (suffix in dataset_suffixes) {
      # Construct dataset name dynamically
      dataset_name <- paste0(prefix, ".dataset.", suffix)
      
      # Read dataset and store it in the list
      microtable_datasets[[dataset_name]] <- read.microtable(data_type, prefix, suffix)
    }
  }
}

# The datasets are now stored in the `microtable_datasets` list.
# Access them using: microtable_datasets[["spe.dataset.main"]], etc.

# If needed, convert the list into individual objects in the global environment:
list2env(microtable_datasets, envir = .GlobalEnv)
```

```{r}

```


