---
title: "Summary Tables for SA's Thesis by AMR"
author: "Alicia Rich"
output:
  html_document:
    theme:
      bootswatch: litera
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    code_folding: "show"
    fig_caption: true
    df_print: paged
params:
  sampleset: "marmoset"
  dataset: "marmoset"
  
---

```{r global, message = FALSE, warning = FALSE}
global             <- config::get(config = "default")

here::i_am("marmoset_tables_SAThesis_AMR.Rmd")
source(here::here(global$setup))

opts_chunk$set(message = FALSE,
               warning = FALSE,
               echo    = TRUE,
               include = TRUE,
               eval    = TRUE,
               comment = "")

subjects <- keep_at(subjects, "marmoset") %>% compact()

```


```{r}
marm_foods <- list(
  "Zoopreem^\u00AE Marmoset Diet" = list(
    "Commercially formulated diet made up of wheat, soybean, egg, alfalfa, and various vitamins",
    1,
    "slice"
  ),
  "Mazuri^\u00AE Callitrichid Gel Diet" = list(
    "Commercially formulated diet made up of soybean, corn, wheat, gelatin, and various vitamins",
    1,
    "slice"
  ),
  "Apple" = list(
    "Cut into 1-cm^2 cubes",
    4,
    "pieces"
  ),
  "Sweet Potato" = list(
    "Cut into 1-cm^2 cubes",
    4,
    "pieces"
  ),
  "Eggs" = list(
    "Scrambled and microwave-cooked",
    2,
    "tsp"
  )
) %>%
  enframe(name = "Food_Item", value = "Details") %>%
  unnest_wider(Details, names_sep = "_") %>%
  rename(Details = Details_1, Amount = Details_2, Unit = Details_3) %>%
  gt(rowname_col = "Food_Item") %>%
  fmt_units() %>%
  cols_merge(columns = c("Amount", "Unit"), pattern = "{1} {2}") %>%
  tab_stubhead("Food Item") %>%
  cols_width(
    stub()  ~ px(250),
    Details ~ px(400),
    Amount  ~ px(100)
  ) %>%
  cols_align("left") %>%
  opt_stylize(style = 3, color = "blue") %>%
  tab_style(style = cell_text(weight = "bold", v_align = "top"), locations = cells_stub()) %>%
  tab_style(style = cell_text(v_align = "top"), locations = cells_body()) %>%
  tab_header("Table X. Standardized diet per marmoset pair") %>%
  tab_style(style = cell_text(align = "left"), locations = cells_title())
marm_foods
gtsave(marm_foods, "marm_foods.png", "visuals")
```

```{r}
marm_diet_trials <- list(
  list(
    "Days"    = c(1, 14),
    "Trials" = list(
      "Group 1" = "Run-in",
      "Group 2" = "Run-in"
    )
  ),
  list(
    "Days"    = c(15, 28),
    "Trials" = list(
      "Group 1" = "Intervention",
      "Group 2" = "Control"
      )
  ),
  list(
    "Days"    = c(29, 42),
    "Trials" = list(
      "Group 1" = "Washout",
      "Group 2" = "Washout"
    )
  ),
  list(
    "Days"    = c(43, 56),
    "Trials" = list(
      "Group 1" = "Control",
      "Group 2" = "Intervention"
    )
  ),
  list(
    "Days"    = c(57, 70),
    "Trials" = list(
      "Group 1" = "Washout",
      "Group 2" = "Washout"
    )
  )
) %>%
  enframe(name = NULL) %>%
  unnest_wider(value) %>%
  unnest_wider(Trials) %>%
  pivot_longer(c("Group 1", "Group 2"), names_to = "Group") %>%
  mutate(Days = str_replace_all(str_remove_all(as.character(Days), "[c()]"), ", ", " - ")) %>%
  pivot_wider(names_from = "Days", values_from = "value") %>%
  gt(rowname_col = "Group") %>%
  opt_table_lines(extent = "none") %>%
  cols_align("center") %>%
  tab_stubhead("Trial Days:") %>%
  tab_header("Table X. Timeline of study") %>%
  tab_style(style = cell_borders(sides = "top", color = "#775F55FF"), locations = cells_body()) %>%
  tab_style(style = cell_borders(sides = "top", color = "#775F55FF"), locations = cells_stub()) %>%
  tab_style_body(style = list(cell_text(transform = "uppercase", weight = "bold"), 
                              cell_fill("#DD8047A6")), pattern = "Intervention") %>%
  tab_style_body(style = list(cell_text(transform = "uppercase"), 
                              cell_fill("#A5AB81A6")), pattern = "Control") %>%
  tab_style_body(style = list(cell_text(style = "oblique", size = "small", color = "#968C8CFF"), 
                              cell_fill("#94B6D2A6")), pattern = "Washout") %>%
  tab_style_body(style = list(cell_text(style = "oblique", size = "small", color = "#968C8CFF"), 
                              cell_fill("#EBDDC3A6")), pattern = "Run-in") %>%
  tab_style(style = list(cell_text(size = "small", transform = "uppercase", weight = "bold", color = "#968C8CFF")),
            locations = cells_column_labels()) %>%
  tab_style(style = list(cell_text(size = "small", transform = "uppercase", weight = "bold", color = "#968C8CFF")),
            locations = cells_stub()) %>%
  tab_style(style = list(cell_text(size = "small", transform = "uppercase", weight = "bold", color = "#968C8CFF")),
            locations = cells_stubhead()) %>%
  tab_style(style = list(cell_text(align = "left"), cell_borders(sides = "bottom", color = "#968C8CFF")),
            locations = cells_title())

marm_diet_trials
gtsave(marm_diet_trials, "marm_diet_trials.png", "visuals")
```


