```{r}
timeline.revised <- assemble_timeline(final.studbook) %>%
  mutate(TypeEvent = if_else(TypeEvent == "End" & ID %in% deceased, "Death", TypeEvent)) %>%
  filter(TypeEvent != "End") %>%
  select(ID, Location, TypeEvent, Date) %>%
  distinct()
```

```{r}
births <- timeline.revised %>%
  filter(TypeEvent == "Birth") %>%
  as_tsibble(key = Date, index = ID, regular = FALSE)
```

```{r}
biographic <- final.studbook %>%
  group_by(ID) %>%
  mutate(DateLast = max(Date),
         LocBirth = if_else(TypeEvent == "Birth"     , Location, NA),
         LocLast  = if_else(OrderLoc == max(OrderLoc), Location, NA)) %>%
  mutate(AgeLast = calculate_age(DateBirth, DateLast)) %>%
  fill(LocBirth) %>%
  fill(LocLast, .direction = "up") %>%
  select(
    ID,
    Status,
    AgeLast,
    Sex,
    Sire,
    Dam,
    DateBirth,
    LocBirth,
    DateLast,
    LocLast
  ) %>% distinct() %>%
  left_join(select(btp25), by = join_by())
```

```{r}
tally_events <- function(df, interval) {
  if (interval == "month") {
    records <- df %>%
      mutate(Date = floor_date(Date, "month"))
    seqby <- paste0("months")
  } else if (interval == "year") {
    records <- df %>%
      mutate(Date = floor_date(Date, "year"))
    seqby <- paste0("years")
  }
  
  list <-  list(pull(records, ID),
                pull(records, Sex), 
                pull(records, Date))
  pmap(list, \(x, y, z) tibble(
    Date = seq(y, by = seqby),
    ID   = x,
    Sex  = z
  )) %>%
    map_depth(., 1, \(x) distinct(x)) %>%
    map_depth(., 1, \(x) arrange(x, Sex, ID)) %>% 
    bind_rows() %>% group_by(Date) %>%
    summarise(Individuals = list(tibble(ID, Sex)), .groups = "drop") %>%
    split(.$Date)
  
}

```

```{r}
count_census_grouped <- function(census, groups) {
  bind_rows(
    map_dfr(names(census), function(date) {
      groups <- census[[date]]
      bind_rows(map_dfr(names(groups), function(group) {
        individuals <- groups[[group]][[1]] 
        tibble(Date           = as.Date(date),
               Group          = group,
               Total          = nrow(individuals),
               Males          = sum(individuals$Sex == "M", na.rm = TRUE),
               Females        = sum(individuals$Sex == "F", na.rm = TRUE),
               Undetermined   = sum(individuals$Sex == "U", na.rm = TRUE))
      }))
    })
  )
}


count_census <- function(census) {
  bind_rows(
    map_dfr(names(census), function(date) {
      individuals <- census[[date]]$Individuals[[1]]  
      tibble(Date           = as.Date(date),
             Total          = nrow(individuals),
             Males          = sum(individuals$Sex == "M", na.rm = TRUE),
             Females        = sum(individuals$Sex == "F", na.rm = TRUE),
             Undetermined   = sum(individuals$Sex == "U", na.rm = TRUE))
    }))
}

```

```{r}
census <- function(df, interval, groups) {
  if (interval == "month") {
    records <- df %>%
      mutate(Birth = floor_date(Birth, "month"),
             End   = floor_date(End, "month"))
    seqby <- paste0("months")
  } else if (interval == "year") {
    records <- df %>%
      mutate(Birth = floor_date(Birth, "year"),
             End   = floor_date(End, "year"))
    seqby <- paste0("years")
  }
  
  list <-  list(pull(records, Birth),
                pull(records, End), 
                pull(records, Sex), 
                pull(records, ID))
  census <- pmap(list, \(w, x, y, z) tibble(
    Date   = seq(w, x, by = seqby),
    ID     = z,
    Sex    = y,
    Cohort = year(w),
    Age    =  calculate_age(w, seq(w, x, by = seqby))
  )) %>% map_depth(., 1, \(x) distinct(x)) %>%
    map_depth(., 1, \(x) arrange(x, Sex, ID)) %>% 
    bind_rows()
  
  if (groups == "age") {
    census %>%
      group_by(Date, Age) %>%
      summarise(Individuals = list(
        tibble(ID, Sex)), 
        .groups = "drop") %>%
      group_by(Date) %>%
      summarise(Ages = split(Individuals, 
                             Age), 
                .groups = "drop") %>%
      split(.$Date) %>%
      map(~ .x$Ages)
  } else if (groups == "cohort") {
    census %>%
      group_by(Date, Cohort) %>%
      summarise(Individuals = list(
        tibble(ID, Sex)), 
        .groups = "drop") %>%
      group_by(Date) %>%
      summarise(Cohorts = split(Individuals, 
                             Cohort), 
                .groups = "drop") %>%
      split(.$Date) %>%
      map(~ .x$Cohorts)
  } else if (groups == "none") {
    census %>%
      group_by(Date) %>%
      summarise(Individuals = list(tibble(ID, Sex, Age)),
                .groups = "drop") %>%
      split(.$Date)
  }
    
}

census.location <- function(df, interval) {
  if (interval == "month") {
    records <- df %>%
      mutate(StartLoc = floor_date(StartLoc, "month"),
             EndLoc   = floor_date(EndLoc, "month"),
             DateBirth = floor_date(DateBirth, "month"))
    seqby <- paste0("months")
  } else if (interval == "year") {
    records <- df %>%
      mutate(StartLoc  = floor_date(StartLoc, "year"),
             EndLoc    = floor_date(EndLoc, "year"),
             DateBirth = floor_date(DateBirth, "year"))
    seqby <- paste0("years")
  }
  
  list <-  list(pull(records, StartLoc),
                pull(records, EndLoc), 
                pull(records, DateBirth), 
                pull(records, Location), 
                pull(records, Sex), 
                pull(records, ID))
  
  pmap(list, \(u, v, w, x, y, z) tibble(
    Date     = seq(u, v, by = seqby),
    ID       = z,
    Location = x,
    Sex      = y,
    Age      =  calculate_age(w, seq(u, v, by = seqby))
  )) %>%
    map_depth(., 1, \(x) distinct(x)) %>%
    map_depth(., 1, \(x) arrange(x, Sex, ID)) %>% 
    bind_rows() %>% 
    group_by(Date, Location) %>%
    summarise(Individuals = list(
      tibble(ID, Sex, Age)), 
      .groups = "drop") %>%
    group_by(Date) %>%
    summarise(Locations = split(Individuals, 
                                Location), 
              .groups = "drop") %>%
    split(.$Date) %>%
    map(~ .x$Locations)
}

print_lambda <- function(lambda) {
 paste0(round((lambda*100) - 100, digits = 2), "% change")
}

```


```{r}
births.deaths <- timeline.revised %>%
  group_by(Age, Cohort, Sex, Date, Event) %>%
  summarize(Count = n()) %>%
  ungroup() %>%
  pivot_wider(id_cols     = c("Age", 
                              "Cohort", 
                              "Sex", 
                              "Date"),
              names_from  = "Event",
              values_from = "Count",
              values_fill = 0) %>%
  select(
         Cohort,
         Sex,
         Date,
         Age,
         Deaths       = Death, 
         Births       = Breed) %>%
  mutate(Sex = case_match(Sex, 
                          "F" ~ "Female",
                          "M" ~ "Male",
                          "U" ~ "Undetermined")) %>%
  arrange(Cohort, Sex, Age) 

births.deaths.total <- births.deaths %>%
  group_by(Cohort, Date, Age) %>%
  summarize(Deaths = sum(Deaths),
            Births = sum(Births)) %>%
  mutate(Sex = "Total") %>%
  ungroup() %>%
  bind_rows(births.deaths) %>%
  arrange(Cohort, Sex, Age) %>%
  filter(Sex != "Undetermined")
```

```{r}
life.table <- final.studbook %>%
  select(
    ID,
    Sex,
    StartLoc,
    EndLoc,
    TypeEvent
  ) %>% 
  filter(TypeEvent != "Transfer") %>%
  mutate(Date = case_match(TypeEvent, 
                           "Birth" ~ StartLoc, 
                           "End"   ~ EndLoc)) %>%
  select(ID, 
         Sex, 
         TypeEvent, 
         Date) %>%
  pivot_wider(id_cols     = c("ID", "Sex"),
              names_from  = "TypeEvent",
              values_from = "Date") %>%
  distinct() %>%
  census(., "year", "cohort") %>% 
  count_census_grouped(., "cohort") %>%
  mutate(Cohort   = as.integer(Group), .keep = "unused") %>%
  pivot_longer(cols      = c("Males", "Females", "Undetermined", "Total"),
               names_to  = "Sex",
               values_to = "Alive") %>%
  filter(Sex != "Undetermined") %>%
  mutate(Sex = case_match(Sex, 
                          "Females"      ~ "Female",
                          "Males"        ~ "Male",
                          "Total"        ~ "Total"),
         Age = year(Date) - Cohort)  %>%
  cohort_grid(., 21, 1988) %>%
  left_join(births.deaths.total, by = join_by(Cohort, Sex, Age, Date)) %>%
  mutate(across(where(is.numeric), ~replace_na(., 0))) %>%
  arrange(Cohort, Sex, Age)  %>%
  group_by(Cohort, Sex) %>%
  mutate(ax   = if_else(Age == 0, 0, lag(Deaths)),
         N0   = if_else(Age == 0, Alive, NA),
         Risk = (Alive + lead(Alive, default = 0)) / 2) %>%
  fill(N0) %>%
  ungroup() %>%
  mutate(lx = if_else(N0 > 0, Alive/N0, 0)) %>%
  group_by(Cohort, Sex) %>%
  mutate(Lx_life = if_else(Age == max(Age), 0, (lx + lead(lx))/2),
         Px      = if_else(Age == max(Age) | lx == 0, 0, lead(lx)/lx)) %>%
  arrange(Cohort, Sex, desc(Age)) %>%
  mutate(Tx = cumsum(Lx_life)) %>%
  ungroup() %>%
  mutate(ex = if_else(lx > 0, Tx / lx, 0),
         qx = if_else(Risk > 0, Deaths / Risk, 0),
         mx = if_else(Risk > 0, 0.5 * Births / Risk, 0)) %>%
  arrange(Cohort, Sex, Age) %>%
  mutate(Fx    = lx * mx) %>%
  mutate(numT  = Age * Fx) %>%
  group_by(Cohort, Sex) %>%
  mutate(R0   = sum(Fx),
         Tnum = sum(numT)) %>%
  ungroup() %>%
  mutate(T = if_else(R0 > 0, Tnum/R0, 0)) %>%
  mutate(lambda_life = if_else(R0 > 0 & T > 0, R0^(1/T), 0)) %>%
  group_by(Cohort, Sex) %>%
  mutate(mleAll     = mle_all(lx, Age),
         mleAge1    = mle_age1(lx, Age),
         FirstRepro = min(Age[mx>0], na.rm = TRUE),
         LastRepro  = max(Age[mx>0], na.rm = TRUE)) %>%
  arrange(Year) %>%
  mutate(lambda_5 = lambda_5(Alive, Year)) %>%
  ungroup() %>%
  arrange(Cohort, Sex, Age) %>%
  mutate(across(where(is.numeric), ~replace_na(., 0))) %>%
  select(
    Cohort,
    Sex,
    N0,
    Date,
    Year,
    Age,
    Nx = Alive,
    lx,
    Px,
    qx,
    ax,
    Lx_life,
    Risk,
    Tx,
    ex,
    Births,
    mx,
    Fx,
    R0,
    T,
    lambda_life,
    lambda_5,
    mleAll,
    mleAge1,
    FirstRepro,
    LastRepro
  )


cohort_grid <- function(df, maxAge, minYear) {
  
  cohorts <- minYear:2025
  years   <- cohorts
  sexes   <- c("Male", "Female", "Total")
  
 grid <-  expand_grid(
    Year   = years,
    Cohort = cohorts,
    Sex    = sexes
  )  %>%
   filter(Year >= Cohort, (Year - Cohort) <= maxAge) %>%
   mutate(Age = Year - Cohort) %>%
   select(Cohort, Year, Sex, Age) %>%
   arrange(Cohort, Sex, Age)
 
 df %>% 
   mutate(Year = year(Date)) %>%
   right_join(grid, by = join_by(
   Year, 
   Age, 
   Cohort, 
   Sex
 )) %>%
   mutate(across(where(is.numeric), ~ replace_na(., 0)),
          Date = make_date(year = Year, month = 1, day = 1)) %>%
   arrange(Cohort, Sex, Age) %>%
   relocate(Cohort, Sex, Year, Age)
}

```



# Projections

## Subsetting Cohorts

We are going to compare three different grouped cohorts based on birth years:

1.  2020 - 2024
2.  2005 - 2009
3.  1990 - 1994

And then run three versions of these time-based subsets:

A.  Females Only
B.  Males Only
C.  Pooled Dynamics

## Build a Leslie Matrix

```{r}
test <- filter(life.table, Cohort >= 2015 & Cohort <= 2024 & Sex == "Female")
```


```{r}
A1 <- build_leslie(life.table, 2015, 2024, "Female")
A2 <- build_leslie(life.table, 2005, 2014, "Female")
A3 <- build_leslie(life.table, 1995, 2004, "Female")
B1 <- build_leslie(life.table, 2015, 2024, "Male"  )
B2 <- build_leslie(life.table, 2005, 2014, "Male"  )
B3 <- build_leslie(life.table, 1995, 2004, "Male"  )
C1 <- build_leslie(life.table, 2015, 2024, "Total" )
C2 <- build_leslie(life.table, 2005, 2014, "Total" )
C3 <- build_leslie(life.table, 1995, 2004, "Total" )

```

```{r}
projections <- pmap()
```


```{r}
projections <- tibble(
  Sex       = rep(c("Females", "Males", "Pooled"), each       = 3),
  Cohorts   = rep(1:3, length.out = 9),
  lambda    = c(
                lambda(A1), 
                lambda(A2), 
                lambda(A3), 
                lambda(B1), 
                lambda(B2), 
                lambda(B3), 
                lambda(C1), 
                lambda(C2), 
                lambda(C3)
                ),
  genTime  = c(
                generation.time(A1), 
                generation.time(A2), 
                generation.time(A3), 
                generation.time(B1), 
                generation.time(B2), 
                generation.time(B3), 
                generation.time(C1), 
                generation.time(C2), 
                generation.time(C3)
                ),
  netReproRate  = c(
                net.reproductive.rate(A1), 
                net.reproductive.rate(A2), 
                net.reproductive.rate(A3), 
                net.reproductive.rate(B1), 
                net.reproductive.rate(B2), 
                net.reproductive.rate(B3), 
                net.reproductive.rate(C1), 
                net.reproductive.rate(C2), 
                net.reproductive.rate(C3))
) %>%
  arrange(Cohorts, Sex)
```

```{r}
life.table.sexes <- count_births(timeline.revised, final.studbook) %>%
      summarize(Births = sum(Births),
                Nx     = n(), 
                .by    = c(BirthYear, Sex, Age)
                ) %>%
      ungroup() %>%
      right_join(
        expand_grid(BirthYear = 1983:2025, 
                    Sex       = c("M", "F"),
                    Age       = 0:22), 
        by = join_by(BirthYear, Sex, Age)
      )  %>%
      mutate(Cohort = as.character(str_glue("{BirthYear}", "{Sex}"))) %>%
  lifeTab() %>%
  select(
    BirthYear,
    Sex,
    Age,
    RiskQx,
    RiskMx,
    N0,
    Nx,
    Px,
    Lx,
    Lx1,
    Qx,
    Qx1,
    Mx,
    R0,
    T,
    MLE,
    lambda,
    FirstRepro,
    LastRepro,
    MaxLongev
  )

life.table <- count_births(timeline.revised, final.studbook) %>%
      summarize(Births = sum(Births),
                Nx     = n(), 
                .by    = c(BirthYear, Age)
                ) %>%
      ungroup() %>%
      right_join(
        expand_grid(BirthYear = 1983:2025, 
                    Age       = 0:22), 
        by = join_by(BirthYear, Age)
      )  %>%
      mutate(Cohort = BirthYear) %>%
  lifeTab() %>%
  select(
    BirthYear,
    Age,
    RiskQx,
    RiskMx,
    N0,
    Nx,
    Px,
    Lx,
    Lx1,
    Qx,
    Qx1,
    Mx,
    R0,
    T,
    MLE,
    lambda,
    FirstRepro,
    LastRepro,
    MaxLongev
  ) %>%
  mutate(Sex = "Total") %>%
  bind_rows(life.table.sexes) %>%
  relocate(Sex, .before = Age) %>%
  arrange(BirthYear, Age, Sex) %>%
  filter(BirthYear + Age <= 2025)

write.table(life.table, here(path$AZAstudbooks$lifetable), sep = "\t", row.names = F)

life.table.visual <- life.table %>%
  mutate(across(c(Px:lambda), ~ round(., digits = 3)))



life.table.static <- life.table.visual %>%
  select(
    BirthYear,
    Sex,
    N0,
    Qx1,
    R0,
    T,
    MLE,
    lambda,
    FirstRepro,
    LastRepro,
    MaxLongev
  ) %>%
  filter(N0 > 0) %>%
  distinct()

write.table(life.table.static, here(path$AZAstudbooks$lifetabStatic), sep = "\t", row.names = F)
```


```{r}
plot_ly(life.table %>% filter(Sex == "Male", BirthYear == case_birthyear),
        x = ~Age, y = ~Lx, color = ~ID, type = "scatter", mode = "lines",
        line = list(width = 1)) %>%
  add_trace(data = life.table %>% filter(ID == case_id),
            x = ~Age, y = ~Lx, name = "Case Male",
            line = list(width = 3, color = "black")) %>%
  layout(title = "Survivorship Curve (Cohort Males)",
         yaxis = list(title = "Lx"),
         xaxis = list(title = "Age"))
```


```{r}
decades <-  expand_grid(
                     Age       = 0:22, 
                     Sex       = c("M", "F"), 
                     BirthYear = 1985:2024) %>%
    full_join(tibble(BirthYear = 1985:2024, 
                     BirthDecade = rep(LETTERS[1:4], each = 10)), 
              by = join_by(BirthYear)) %>%
   select(BirthDecade, BirthYear, Sex, Age) %>%
  arrange(BirthDecade, BirthYear, Sex, Age) %>%
  filter(BirthYear + Age <= 2025)

years5 <-  expand_grid(
                     Age         = 0:22, 
                     Sex         = c("M", "F"), 
                     BirthYear   = 1985:2024) %>%
    full_join(tibble(BirthYear   = 1985:2024, 
                     BirthCohort = rep(LETTERS[1:8], each = 5)), 
              by = join_by(BirthYear)) %>%
   select(BirthCohort, BirthYear, Sex, Age) %>%
  arrange(BirthCohort, BirthYear, Sex, Age) %>%
  filter(BirthYear + Age <= 2025)

```

```{r}
life.table <- count_births(timeline.revised, final.studbook) %>%
      summarize(Births = sum(Births),
                Nx     = n(), 
                .by    = c(BirthYear, Age)
                ) %>%
      ungroup() %>%
      right_join(distinct(decades, 
                          Age, 
                          BirthYear, 
                          BirthDecade), 
                 by = join_by(BirthYear, Age)) %>%
  mutate(Cohort = BirthDecade, across(c(Births, Nx), ~ replace_na(., 0))) %>%
  summarize(Births = sum(Births),
           Nx      = sum(Nx), 
           .by     = c(BirthDecade, Cohort, Age)) %>%
  arrange(BirthDecade, Age) %>%
  lifeTab() %>%
  select(
    BirthDecade,
    Age,
    RiskQx,
    RiskMx,
    N0,
    Nx,
    Px,
    Lx,
    Lx1,
    Qx,
    Qx1,
    Mx,
    R0,
    T,
    MLE,
    lambda,
    FirstRepro,
    LastRepro,
    MaxLongev
  ) %>%
  mutate(Sex = "Total") %>%
  bind_rows(life.table.sexes) %>%
  relocate(Sex, .before = Age) %>%
  arrange(BirthDecade, Age, Sex)

```

```{r}
life.table.visual <- life.table %>%
  mutate(across(c(Px:lambda), ~ round(., digits = 3)))

life.table.static <- life.table.visual %>%
  select(
    BirthDecade,
    Sex,
    N0,
    Qx1,
    R0,
    T,
    MLE,
    lambda,
    FirstRepro,
    LastRepro,
    MaxLongev
  ) %>%
  filter(N0 > 0) %>%
  distinct() %>%
  arrange(BirthDecade, Sex) %>%
  mutate(CohortLabel = case_match(
    BirthDecade,
    "A" ~ "1985-1994",
    "B" ~ "1995-2004",
    "C" ~ "2005-2014\n(Culi)",
    "D" ~ "2015-2024\n(Warble)"
  )) %>%
  relocate(CohortLabel, .after = BirthDecade)

```


